name: Update Face Recognition Data
on:
  push:
    paths:
      - 'web_data.json'
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Commit updates
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add web_data.json
        git commit -m "Update face recognition data [skip ci]" || echo "No changes to commit"
        git push
